version: '3.8'
services:
  node1:
    image: blockchain
    container_name: node1
    hostname: node1
    networks:
      - blockchain
    command: "8001"

  node2:
    image: blockchain
    container_name: node2
    hostname: node2
    networks:
      - blockchain
    command: "8002"

  node3:
    image: blockchain
    container_name: node3
    hostname: node3
    networks:
      - blockchain
    command: "8003"

networks:
  blockchain: